#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: The talking bit
lang: es-ES
short: TalkingBit

# Short bio or description (displayed in the header)
description: Personal learning journal about programming, maybe more.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/16079996?s=460&v=4
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footerlinks:
  email: franiglesias@mac.com
  github: franiglesias
  linkedin: franiglesias
  rss: yes
  youtube: TalkingBit
  leanpub: franiglesias

# comment box project id
commentbox: 5714057684320256-proj

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://franiglesias.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Especificar explícitamente que no se use un tema
theme: null

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  load_paths: assets/css
  style: expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-tagging

tag_page_layout: tagpage
tag_page_dir: tag
tag_feed_layout: tagfeed
tag_feed_dir: tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

future: false
